infrastructureVersion: v1

services:
  - type: web
    name: my-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    autoDeploy: true

  - type: static_site
    name: my-frontend
    staticPublishPath: .
    branch: main
    autoDeploy: true
