services:
  - type: web
    name: minecraft-site-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGODB_URI_HERE
    repo: https://github.com/tann12345/MyMcSite
    branch: main

  - type: static
    name: minecraft-site-frontend
    env: static
    buildCommand: ''
    staticPublishPath: frontend
    repo: https://github.com/tann12345/MyMcSite
    branch: main
