services:
  - type: web
    name: my-backend
    env: python
    buildCommand: pip install -r requirements.txt || true
    startCommand: python app.py
    branch: main
    autoDeploy: true

  - type: static
    name: my-frontend
    staticPublishPath: .
    branch: main
    autoDeploy: true
