services:
  - type: web
    name: mc-bot-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/bot.js
    branch: main
    autoDeploy: true

  - type: static
    name: mc-bot-frontend
    staticPublishPath: frontend
    branch: main
    autoDeploy: true
